version: "3"
services:

  app:
    build: .
    ports:
     - 12000:80
    volumes:
     - .:/var/www
    environment:
      APP_MODE: frontend
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  app_backend:
    build: .
    ports:
     - 12001:80
    volumes:
     - .:/var/www
    environment:
      APP_MODE: backend
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # Mysql Databases
  mysql:
    build: ./docker/mariadb
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
     - 12010:80
    environment:
      PMA_HOST: mysql
    restart: always

volumes:
  data: